"use client";

import React from 'react';
import { format } from 'date-fns';
import { cn } from '@/lib/utils';
import Logo from '@/components/Logo';
import { 
  ShieldAlert, CheckCircle2, AlertCircle, 
  Target, Zap, TrendingUp, Clock, Building2 
} from 'lucide-react';

interface CustomerReportTemplateProps {
  data: any;
}

const CustomerReportTemplate = ({ data }: CustomerReportTemplateProps) => {
  if (!data || !data.intelligence) return null;

  const { intelligence, journey, customerName } = data;
  const summary = intelligence.ai_summary;

  return (
    <div id="customer-report-template" className="bg-white text-slate-900 p-12 w-[1000px] font-sans hidden">
      
      {/* 1. Cover Page */}
      <div className="h-[1200px] flex flex-col justify-between border-b-8 border-indigo-600 pb-20">
        <div className="flex justify-between items-start">
          <Logo className="h-10 w-auto text-indigo-600 fill-current" />
          <div className="text-right">
            <p className="text-[10px] font-black uppercase tracking-[0.3em] text-slate-400">Enterprise Intelligence Report</p>
            <p className="text-sm font-bold text-slate-600">{format(new Date(), 'MMMM yyyy')}</p>
          </div>
        </div>

        <div className="space-y-6">
          <h1 className="text-7xl font-black tracking-tighter text-slate-900 leading-none">
            Customer <br /> Intelligence <br /> Report
          </h1>
          <div className="h-2 w-32 bg-indigo-600" />
          <div className="space-y-2">
            <p className="text-2xl font-bold text-slate-600">Account: <span className="text-indigo-600">{customerName}</span></p>
            <p className="text-lg font-medium text-slate-400">Generated by Aerchain AI Engine</p>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-12">
          <div className="space-y-1">
            <p className="text-[10px] font-black uppercase tracking-widest text-slate-400">Health Score</p>
            <p className="text-4xl font-black text-slate-900">{intelligence.health_score}/100</p>
          </div>
          <div className="space-y-1">
            <p className="text-[10px] font-black uppercase tracking-widest text-slate-400">SLA Risk</p>
            <p className="text-4xl font-black text-rose-600">{intelligence.sla_risk}</p>
          </div>
          <div className="space-y-1">
            <p className="text-[10px] font-black uppercase tracking-widest text-slate-400">Open Tickets</p>
            <p className="text-4xl font-black text-slate-900">{intelligence.open_tickets}</p>
          </div>
        </div>
      </div>

      {/* 2. Executive Summary */}
      <div className="py-20 space-y-12">
        <div className="space-y-4">
          <h2 className="text-3xl font-black tracking-tight flex items-center gap-3">
            <ShieldAlert className="h-8 w-8 text-indigo-600" />
            Executive Summary
          </h2>
          <div className="p-8 rounded-[32px] bg-slate-50 border border-slate-100">
            <p className="text-xl font-medium leading-relaxed text-slate-800 italic">
              "{customerName} is currently at <span className="text-rose-600 font-black">{intelligence.status.toUpperCase()}</span> with a health score of {intelligence.health_score}. 
              Key concerns include {intelligence.sla_risk.toLowerCase()} SLA adherence and a backlog of {intelligence.open_tickets} tickets. 
              The {summary.dominant_issue?.module} module is the primary contributor, accounting for {summary.dominant_issue?.contribution}% of all issues."
            </p>
          </div>
        </div>

        {/* 3. AI Insights Grid */}
        <div className="grid grid-cols-2 gap-8">
          <div className="space-y-6">
            <h3 className="text-xs font-black uppercase tracking-widest text-emerald-600 flex items-center gap-2">
              <CheckCircle2 className="h-4 w-4" /> What's Going Well
            </h3>
            <ul className="space-y-4">
              {summary.good.map((item: string, i: number) => (
                <li key={i} className="flex items-start gap-3 text-sm font-bold text-slate-700">
                  <div className="h-1.5 w-1.5 rounded-full bg-emerald-500 mt-2 shrink-0" />
                  {item}
                </li>
              ))}
            </ul>
          </div>
          <div className="space-y-6">
            <h3 className="text-xs font-black uppercase tracking-widest text-rose-600 flex items-center gap-2">
              <AlertCircle className="h-4 w-4" /> What's Going Wrong
            </h3>
            <ul className="space-y-4">
              {summary.bad.map((item: string, i: number) => (
                <li key={i} className="flex items-start gap-3 text-sm font-bold text-slate-700">
                  <div className="h-1.5 w-1.5 rounded-full bg-rose-500 mt-2 shrink-0" />
                  {item}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {/* 4. Issue Analysis & Recommendations */}
      <div className="py-20 space-y-12 border-t border-slate-100">
        <div className="grid grid-cols-2 gap-12">
          <div className="space-y-6">
            <h3 className="text-xs font-black uppercase tracking-widest text-amber-600 flex items-center gap-2">
              <Target className="h-4 w-4" /> Top Issues (Root Causes)
            </h3>
            <div className="space-y-4">
              {summary.issues.map((item: string, i: number) => (
                <div key={i} className="p-4 rounded-2xl bg-amber-50 border border-amber-100 text-sm font-bold text-amber-900">
                  {item}
                </div>
              ))}
            </div>
          </div>
          <div className="space-y-6">
            <h3 className="text-xs font-black uppercase tracking-widest text-indigo-600 flex items-center gap-2">
              <Zap className="h-4 w-4" /> Recommended Actions
            </h3>
            <div className="space-y-4">
              {summary.actions.map((item: string, i: number) => (
                <div key={i} className="p-4 rounded-2xl bg-indigo-50 border border-indigo-100 text-sm font-black text-indigo-900">
                  {i + 1}. {item}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Dominant Issue Highlight */}
        {summary.dominant_issue && (
          <div className="p-8 rounded-[32px] bg-rose-600 text-white space-y-4">
            <div className="flex items-center gap-3">
              <ShieldAlert className="h-8 w-8" />
              <h4 className="text-2xl font-black tracking-tight">Critical Module Impact</h4>
            </div>
            <p className="text-lg font-bold opacity-90">
              The {summary.dominant_issue.module} module is causing {summary.dominant_issue.contribution}% of all support interactions. 
              This is the primary driver of SLA breaches and customer dissatisfaction.
            </p>
          </div>
        )}
      </div>

      {/* 5. Appendix / Metadata */}
      <div className="py-20 border-t border-slate-100 flex justify-between items-end">
        <div className="space-y-1">
          <p className="text-[10px] font-black uppercase tracking-widest text-slate-400">Report Metadata</p>
          <p className="text-xs font-bold text-slate-500">Confidence Score: {intelligence.confidence}%</p>
          <p className="text-xs font-bold text-slate-500">Data Range: Last 6 Months</p>
        </div>
        <p className="text-[10px] font-black uppercase tracking-[0.3em] text-slate-300">Aerchain Support Intelligence System</p>
      </div>
    </div>
  );
};

export default CustomerReportTemplate;